# alembic/script.py.mako
"""Remove user foreign keys from alert models

Revision ID: 40e7177c3a3a
Revises: b036da490a82
Create Date: 2025-12-15 09:41:31.655638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e7177c3a3a'
down_revision = 'b036da490a82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alert_rules_created_by_fkey', 'alert_rules', type_='foreignkey')
    op.drop_constraint('alerts_acknowledged_by_fkey', 'alerts', type_='foreignkey')
    op.drop_constraint('alerts_resolved_by_fkey', 'alerts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('alerts_resolved_by_fkey', 'alerts', 'users', ['resolved_by'], ['id'])
    op.create_foreign_key('alerts_acknowledged_by_fkey', 'alerts', 'users', ['acknowledged_by'], ['id'])
    op.create_foreign_key('alert_rules_created_by_fkey', 'alert_rules', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
    