# alembic/script.py.mako
"""Make alert_rules created_by nullable

Revision ID: 822d1927fd3f
Revises: ec8a914eaf50
Create Date: 2025-12-15 09:23:26.938887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822d1927fd3f'
down_revision = 'ec8a914eaf50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    