# alembic/script.py.mako
"""Make alert_rules created_by nullable

Revision ID: b036da490a82
Revises: 822d1927fd3f
Create Date: 2025-12-15 09:24:28.804487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b036da490a82'
down_revision = '822d1927fd3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    